// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZdjH7FgqAdxpbFfyd6uLhhW1rMCI211c',
    appId: '1:770205798301:web:1f18dd0dc823405dc1a974',
    messagingSenderId: '770205798301',
    projectId: 'carangode-visits',
    authDomain: 'carangode-visits.firebaseapp.com',
    storageBucket: 'carangode-visits.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANeC4fKSWIZ9yaX4jUeP9aLyovrVsuZTY',
    appId: '1:770205798301:android:f045da8d7ad1d5bec1a974',
    messagingSenderId: '770205798301',
    projectId: 'carangode-visits',
    storageBucket: 'carangode-visits.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ2tp3h39wHfQ2ALm0uOyTpIF3feDPmHY',
    appId: '1:770205798301:ios:f8e3821243ce690cc1a974',
    messagingSenderId: '770205798301',
    projectId: 'carangode-visits',
    storageBucket: 'carangode-visits.firebasestorage.app',
    iosBundleId: 'com.example.carangodeVisitsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ2tp3h39wHfQ2ALm0uOyTpIF3feDPmHY',
    appId: '1:770205798301:ios:f8e3821243ce690cc1a974',
    messagingSenderId: '770205798301',
    projectId: 'carangode-visits',
    storageBucket: 'carangode-visits.firebasestorage.app',
    iosBundleId: 'com.example.carangodeVisitsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZdjH7FgqAdxpbFfyd6uLhhW1rMCI211c',
    appId: '1:770205798301:web:d65ca99f31867e44c1a974',
    messagingSenderId: '770205798301',
    projectId: 'carangode-visits',
    authDomain: 'carangode-visits.firebaseapp.com',
    storageBucket: 'carangode-visits.firebasestorage.app',
  );
}
